#!/bin/bash

echo "🔍 Debug del token de Google"
echo "============================="
echo ""

echo "📋 Pasos para debuggear:"
echo "1. Abre http://localhost:3000"
echo "2. Abre la consola del navegador (F12)"
echo "3. Haz login con Google"
echo "4. Verifica que aparezca: 'Token de Google almacenado: [token]'"
echo "5. Ve a la pestaña Calendario"
echo "6. Verifica que aparezca: 'Token de acceso encontrado: Sí'"
echo "7. Verifica que aparezca: 'Enviando token al backend: Sí'"
echo "8. Verifica que aparezca: 'Respuesta del backend: 200 OK'"
echo ""

echo "🔧 Si no funciona:"
echo "1. Verifica que Google esté habilitado en Firebase Console"
echo "2. Verifica que los dominios estén autorizados en Google Cloud Console"
echo "3. Verifica que las APIs estén habilitadas"
echo "4. Revisa los errores en la consola del navegador"
echo "5. Revisa los logs del servidor en la terminal"
echo ""

echo "📱 URLs importantes:"
echo "- Frontend: http://localhost:3000"
echo "- Backend: http://localhost:3001"
echo "- Firebase Console: https://console.firebase.google.com"
echo "- Google Cloud Console: https://console.cloud.google.com"
echo ""

echo "🎯 Estado esperado:"
echo "✅ Login con Google funciona"
echo "✅ Token se almacena en localStorage"
echo "✅ Calendario muestra eventos reales"
echo "✅ Email muestra emails reales"
echo ""

echo "🚀 Para debuggear:"
echo "1. Abre la consola del navegador (F12)"
echo "2. Haz login con Google"
echo "3. Revisa los logs que aparecen"
echo "4. Comparte cualquier error que veas"
echo ""

echo "📊 Logs del servidor:"
echo "Revisa la terminal donde está corriendo el backend"
echo "Deberías ver logs como:"
echo "- 📅 Recibiendo solicitud de eventos del calendario"
echo "- 🔑 Configurando OAuth2 con token: [token]..."
echo "- ✅ Eventos obtenidos: [número]"
