#!/bin/bash

echo "🔍 Debugging de tokens y autenticación..."
echo ""

echo "📋 Instrucciones para debugging:"
echo ""
echo "1. 🌐 Abre http://localhost:3000 en tu navegador"
echo ""
echo "2. 🔐 Inicia sesión con Google si no lo has hecho"
echo ""
echo "3. 🛠️ Abre las herramientas de desarrollador (F12)"
echo ""
echo "4. 📝 Ejecuta estos comandos en la consola:"
echo ""
echo "   // Verificar usuario autenticado"
echo "   console.log('Usuario:', firebase.auth().currentUser)"
echo ""
echo "   // Verificar tokens en localStorage"
echo "   console.log('Token:', localStorage.getItem('googleAccessToken'))"
echo "   console.log('Expiry:', localStorage.getItem('googleTokenExpiry'))"
echo ""
echo "   // Verificar si el token ha expirado"
echo "   const expiry = localStorage.getItem('googleTokenExpiry')"
echo "   if (expiry) {"
echo "     console.log('Token expira en:', new Date(parseInt(expiry)))"
echo "     console.log('¿Ha expirado?', Date.now() > parseInt(expiry))"
echo "   }"
echo ""
echo "   // Probar obtener token fresco"
echo "   firebase.auth().currentUser?.getIdToken().then(token => {"
echo "     console.log('Token fresco:', token)"
echo "   })"
echo ""
echo "5. 🔄 Si no hay token, cierra sesión y vuelve a iniciar sesión"
echo ""
echo "6. 🚀 Recarga la página (Ctrl+Shift+R) después de verificar los tokens"
echo ""
echo "💡 Si sigues teniendo problemas:"
echo "   - Limpia el localStorage: localStorage.clear()"
echo "   - Recarga la página"
echo "   - Inicia sesión nuevamente"
