#!/bin/bash

echo "🔧 Habilitando APIs de Google automáticamente"
echo "============================================="
echo ""

echo "📋 PASO 1: Habilitar Google Calendar API"
echo "========================================"
echo "1. Ve a: https://console.developers.google.com/apis/api/calendar-json.googleapis.com/overview?project=your-project-id"
echo "2. Haz clic en 'ENABLE'"
echo "3. Espera unos minutos para que se propague"
echo ""

echo "📋 PASO 2: Habilitar Gmail API"
echo "=============================="
echo "1. Ve a: https://console.developers.google.com/apis/api/gmail.googleapis.com/overview?project=your-project-id"
echo "2. Haz clic en 'ENABLE'"
echo "3. Espera unos minutos para que se propague"
echo ""

echo "📋 PASO 3: Habilitar Google Identity API"
echo "==================================="
echo "1. Ve a: https://console.developers.google.com/apis/api/identity.googleapis.com/overview?project=your-project-id"
echo "2. Haz clic en 'ENABLE'"
echo "3. Espera unos minutos para que se propague"
echo ""

echo "📋 PASO 4: Verificar configuración OAuth"
echo "======================================="
echo "1. Ve a: https://console.cloud.google.com/apis/credentials?project=your-project-id"
echo "2. Verifica que tengas un OAuth 2.0 Client ID"
echo "3. Si no tienes, crea uno:"
echo "   - Tipo: Web application"
echo "   - Nombre: Sensa OS Web Client"
echo "   - Authorized JavaScript origins:"
echo "     - http://localhost:3000"
echo "     - https://tu-dominio.railway.app (si ya tienes uno)"
echo "   - Authorized redirect URIs:"
echo "     - http://localhost:3000"
echo "     - https://tu-dominio.railway.app (si ya tienes uno)"
echo ""

echo "📋 PASO 5: Verificar Firebase Console"
echo "====================================="
echo "1. Ve a: https://console.firebase.google.com/project/sensa-os-ac840/authentication/providers"
echo "2. Verifica que Google esté habilitado"
echo "3. Si no está, habilítalo:"
echo "   - Haz clic en Google"
echo "   - Activa 'Enable'"
echo "   - Project support email: tu-email@gmail.com"
echo "   - Web SDK configuration: ON"
echo ""

echo "🔧 Mientras tanto, usando datos de ejemplo..."
echo "============================================="
echo ""

echo "📱 URLs importantes:"
echo "==================="
echo "- Google Cloud Console: https://console.cloud.google.com"
echo "- Firebase Console: https://console.firebase.google.com"
echo "- Proyecto: sensa-os-ac840 (ID: your-project-id)"
echo ""

echo "🎯 Estado esperado:"
echo "=================="
echo "✅ APIs habilitadas en Google Cloud Console"
echo "✅ OAuth 2.0 configurado correctamente"
echo "✅ Google habilitado en Firebase Console"
echo "✅ Calendario muestra eventos reales"
echo "✅ Email muestra emails reales"
echo ""

echo "🚀 Para probar:"
echo "==============="
echo "1. Habilita las APIs en Google Cloud Console"
echo "2. Espera unos minutos"
echo "3. Recarga la aplicación"
echo "4. Deberías ver datos reales de Google"
echo ""

echo "⚠️ Nota: Mientras las APIs no estén habilitadas,"
echo "   la aplicación mostrará datos de ejemplo"
echo "   para que puedas probar todas las funcionalidades."
