#!/bin/bash

echo "🔧 Habilitando solo las APIs que funcionan"
echo "=========================================="
echo ""

echo "📋 PASO 1: Habilitar Google Calendar API"
echo "========================================"
echo "1. Ve a: https://console.cloud.google.com/apis/library/calendar-json.googleapis.com?project=your-project-id"
echo "2. Haz clic en 'ENABLE'"
echo "3. Espera unos minutos para que se propague"
echo ""

echo "📋 PASO 2: Habilitar Gmail API"
echo "=============================="
echo "1. Ve a: https://console.cloud.google.com/apis/library/gmail.googleapis.com?project=your-project-id"
echo "2. Haz clic en 'ENABLE'"
echo "3. Espera unos minutos para que se propague"
echo ""

echo "📋 PASO 3: Verificar OAuth 2.0 Client ID"
echo "======================================="
echo "1. Ve a: https://console.cloud.google.com/apis/credentials?project=your-project-id"
echo "2. Verifica que tengas un OAuth 2.0 Client ID"
echo "3. Si no tienes, crea uno:"
echo "   - Tipo: Web application"
echo "   - Nombre: Sensa OS Web Client"
echo "   - Authorized JavaScript origins:"
echo "     - http://localhost:3000"
echo "   - Authorized redirect URIs:"
echo "     - http://localhost:3000"
echo ""

echo "📋 PASO 4: Verificar Firebase Console"
echo "===================================="
echo "1. Ve a: https://console.firebase.google.com/project/sensa-os-ac840/authentication/providers"
echo "2. Verifica que Google esté habilitado"
echo "3. Si no está, habilítalo:"
echo "   - Haz clic en Google"
echo "   - Activa 'Enable'"
echo "   - Project support email: tu-email@gmail.com"
echo "   - Web SDK configuration: ON"
echo ""

echo "🎯 APIs que funcionan:"
echo "======================"
echo "✅ Google Calendar API"
echo "✅ Gmail API"
echo "❌ Google Identity API (no existe o no está disponible)"
echo ""

echo "🚀 Para probar:"
echo "==============="
echo "1. Habilita solo Google Calendar API y Gmail API"
echo "2. Espera unos minutos"
echo "3. Recarga la aplicación"
echo "4. Deberías ver datos reales de Google"
echo ""

echo "⚠️ Nota: Google Identity API no es necesaria."
echo "   Las APIs de Calendar y Gmail son suficientes para el funcionamiento."
