#!/bin/bash

echo "🔧 Configuración automática de Firebase Authentication"
echo "=================================================="
echo ""

echo "📋 PASO 1: Verificar configuración actual"
echo "=========================================="

# Verificar si Firebase está configurado
if [ -f ".env" ]; then
    echo "✅ Archivo .env encontrado"
    source .env
    echo "   Project ID: $VITE_FIREBASE_PROJECT_ID"
    echo "   Auth Domain: $VITE_FIREBASE_AUTH_DOMAIN"
else
    echo "❌ Archivo .env no encontrado"
    exit 1
fi

echo ""
echo "📋 PASO 2: Configurar Firebase Authentication"
echo "============================================="
echo ""
echo "🔑 Necesitas hacer esto en Firebase Console:"
echo ""
echo "1. Ve a https://console.firebase.google.com"
echo "2. Selecciona tu proyecto: $VITE_FIREBASE_PROJECT_ID"
echo "3. Ve a 'Authentication' → 'Sign-in method'"
echo "4. Habilita 'Google' como proveedor"
echo "5. Configura:"
echo "   - Web SDK configuration: ON"
echo "   - Project support email: tu-email@gmail.com"
echo "   - Web client ID: (se genera automáticamente)"
echo "   - Web client secret: (se genera automáticamente)"
echo ""
echo "6. En 'Authorized domains' agrega:"
echo "   - localhost"
echo "   - tu-dominio.railway.app (para producción)"
echo ""

echo "📋 PASO 3: Verificar Google Cloud Console"
echo "========================================="
echo ""
echo "🔑 Necesitas hacer esto en Google Cloud Console:"
echo ""
echo "1. Ve a https://console.cloud.google.com"
echo "2. Selecciona tu proyecto: $VITE_FIREBASE_PROJECT_ID"
echo "3. Ve a 'APIs & Services' → 'Credentials'"
echo "4. Verifica que tengas:"
echo "   - OAuth 2.0 Client ID configurado"
echo "   - Authorized JavaScript origins:"
echo "     - http://localhost:3000"
echo "     - https://tu-dominio.railway.app"
echo "   - Authorized redirect URIs:"
echo "     - http://localhost:3000"
echo "     - https://tu-dominio.railway.app"
echo ""

echo "📋 PASO 4: Verificar APIs habilitadas"
echo "====================================="
echo ""
echo "🔑 En Google Cloud Console, ve a 'APIs & Services' → 'Library'"
echo "   y habilita estas APIs:"
echo "   ✅ Google Calendar API"
echo "   ✅ Gmail API"
echo "   ✅ Google Identity API"
echo ""

echo "📋 PASO 5: Probar la aplicación"
echo "==============================="
echo ""
echo "1. Abre http://localhost:3000"
echo "2. Haz login con Google"
echo "3. Verifica que aparezca el token en la consola"
echo "4. Ve a Calendario y Email"
echo "5. Deberías ver datos reales de Google"
echo ""

echo "🔧 Si sigue sin funcionar:"
echo "========================="
echo ""
echo "1. Verifica que Google esté habilitado en Firebase"
echo "2. Verifica que los dominios estén autorizados"
echo "3. Verifica que las APIs estén habilitadas"
echo "4. Revisa la consola del navegador para errores"
echo ""

echo "📱 URLs importantes:"
echo "==================="
echo "- Frontend: http://localhost:3000"
echo "- Backend: http://localhost:3001"
echo "- Firebase Console: https://console.firebase.google.com"
echo "- Google Cloud Console: https://console.cloud.google.com"
echo ""

echo "🎯 Estado esperado:"
echo "=================="
echo "✅ Login con Google funciona"
echo "✅ Token se almacena correctamente"
echo "✅ Calendario muestra eventos reales"
echo "✅ Email muestra emails reales"
echo ""

echo "🚀 ¡Listo! Ahora configura Firebase y Google Cloud Console"
