#!/bin/bash

echo "🔧 Solucionando problema de proyecto"
echo "==================================="
echo ""

echo "📋 PROBLEMA IDENTIFICADO:"
echo "========================"
echo "❌ Estás usando: sensa-os-ac840 (nombre del proyecto)"
echo "✅ Debes usar: your-project-id (ID numérico del proyecto)"
echo ""

echo "📋 PASO 1: Habilitar Google Identity API (con ID correcto)"
echo "=========================================================="
echo "1. Ve a: https://console.cloud.google.com/apis/library/identity.googleapis.com?project=your-project-id"
echo "2. Haz clic en 'ENABLE'"
echo "3. Espera unos minutos para que se propague"
echo ""

echo "📋 PASO 2: Verificar todas las APIs (con ID correcto)"
echo "===================================================="
echo "1. Ve a: https://console.cloud.google.com/apis/library?project=your-project-id"
echo "2. Busca y verifica que estén habilitadas:"
echo "   ✅ Google Calendar API"
echo "   ✅ Gmail API"
echo "   ✅ Google Identity API"
echo ""

echo "📋 PASO 3: Verificar OAuth 2.0 Client ID (con ID correcto)"
echo "========================================================="
echo "1. Ve a: https://console.cloud.google.com/apis/credentials?project=your-project-id"
echo "2. Verifica que tengas un OAuth 2.0 Client ID"
echo "3. Si no tienes, crea uno:"
echo "   - Tipo: Web application"
echo "   - Nombre: Sensa OS Web Client"
echo "   - Authorized JavaScript origins:"
echo "     - http://localhost:3000"
echo "   - Authorized redirect URIs:"
echo "     - http://localhost:3000"
echo ""

echo "📋 PASO 4: Verificar Firebase Console"
echo "===================================="
echo "1. Ve a: https://console.firebase.google.com/project/sensa-os-ac840/authentication/providers"
echo "2. Verifica que Google esté habilitado"
echo "3. Si no está, habilítalo:"
echo "   - Haz clic en Google"
echo "   - Activa 'Enable'"
echo "   - Project support email: tu-email@gmail.com"
echo "   - Web SDK configuration: ON"
echo ""

echo "🎯 DIFERENCIA IMPORTANTE:"
echo "========================"
echo "❌ NO uses: sensa-os-ac840 (nombre del proyecto)"
echo "✅ SÍ usa: your-project-id (ID numérico del proyecto)"
echo ""

echo "🚀 Para probar:"
echo "==============="
echo "1. Usa el ID numérico your-project-id en todas las URLs"
echo "2. Habilita Google Identity API con el enlace correcto"
echo "3. Espera unos minutos"
echo "4. Recarga la aplicación"
echo "5. Deberías ver datos reales de Google"
echo ""

echo "⚠️ Nota: El problema era usar el nombre del proyecto en lugar del ID numérico."
echo "   Google Cloud Console necesita el ID numérico para funcionar correctamente."
