#!/bin/bash

echo "🚀 Configuración completa para producción"
echo "========================================"
echo ""

echo "📋 PASO 1: Instalar Railway CLI (si no está instalado)"
echo "======================================================"
if ! command -v railway &> /dev/null; then
    echo "Instalando Railway CLI..."
    npm install -g @railway/cli
else
    echo "✅ Railway CLI ya está instalado"
fi

echo ""
echo "📋 PASO 2: Login en Railway"
echo "==========================="
echo "Ejecuta manualmente: railway login"
echo "Esto abrirá el navegador para autorizar"
echo ""

echo "📋 PASO 3: Crear proyecto en Railway"
echo "===================================="
echo "Ejecuta manualmente: railway init"
echo "Selecciona: 'Create new project'"
echo "Nombre: 'sensa-os'"
echo ""

echo "📋 PASO 4: Obtener URL de producción"
echo "===================================="
echo "Ejecuta manualmente: railway domain"
echo "Copia la URL que aparece (ejemplo: sensa-os-production.railway.app)"
echo ""

echo "📋 PASO 5: Configurar variables de entorno"
echo "=========================================="
echo "Ejecuta manualmente: railway variables"
echo "Agrega estas variables una por una:"
echo ""
echo "VITE_FIREBASE_API_KEY=AIzaSyD99fYsZaNO5ystn7bOdy20dTWpErQVoz8"
echo "VITE_FIREBASE_AUTH_DOMAIN=sensa-os-ac840.firebaseapp.com"
echo "VITE_FIREBASE_PROJECT_ID=sensa-os-ac840"
echo "VITE_FIREBASE_STORAGE_BUCKET=sensa-os-ac840.firebasestorage.app"
echo "VITE_FIREBASE_MESSAGING_SENDER_ID=your-project-id"
echo "VITE_FIREBASE_APP_ID=1:your-project-id:web:2b115f20a44c131b2fdcb4"
echo "GOOGLE_CLIENT_ID=169191147456-776mv4fff2f81rp76jig5dpc39604ht7.apps.googleusercontent.com"
echo "GOOGLE_CLIENT_SECRET=your-google-client-secret"
echo ""

echo "📋 PASO 6: Desplegar"
echo "===================="
echo "Ejecuta manualmente: railway up"
echo "Espera a que termine el despliegue"
echo ""

echo "📋 PASO 7: Configurar Google Cloud Console"
echo "=========================================="
echo "1. Ve a https://console.cloud.google.com"
echo "2. Proyecto: sensa-os-ac840"
echo "3. APIs & Services → Credentials"
echo "4. Busca: 169191147456-776mv4fff2f81rp76jig5dpc39604ht7.apps.googleusercontent.com"
echo "5. Haz clic en el icono de editar (lápiz)"
echo "6. En 'Authorized JavaScript origins' agrega:"
echo "   - https://TU-DOMINIO.railway.app"
echo "7. En 'Authorized redirect URIs' agrega:"
echo "   - https://TU-DOMINIO.railway.app"
echo "8. Haz clic en 'SAVE'"
echo ""

echo "📋 PASO 8: Configurar Firebase Console"
echo "======================================"
echo "1. Ve a https://console.firebase.google.com"
echo "2. Proyecto: sensa-os-ac840"
echo "3. Authentication → Settings → Authorized domains"
echo "4. Agrega: TU-DOMINIO.railway.app"
echo "5. Haz clic en 'ADD'"
echo ""

echo "📋 PASO 9: Habilitar APIs en Google Cloud"
echo "========================================="
echo "1. Ve a https://console.cloud.google.com/apis/library"
echo "2. Busca y habilita:"
echo "   - Google Calendar API"
echo "   - Gmail API"
echo "   - Google Identity API"
echo ""

echo "🎯 Resultado esperado:"
echo "======================"
echo "✅ Aplicación funcionando en https://TU-DOMINIO.railway.app"
echo "✅ Login con Google funcionando"
echo "✅ Calendario con datos reales"
echo "✅ Email con datos reales"
echo ""

echo "🚀 ¡Sigue estos pasos y tendrás Sensa OS funcionando en producción!"
