#!/bin/bash

echo "🔧 Actualizando Client ID real"
echo "=============================="
echo ""

echo "📋 Client ID actual:"
echo "==================="
echo "❌ Anterior: 169191147456-776mv4fff2f81rp76jig5dpc39604ht7.apps.googleusercontent.com"
echo "✅ Nuevo: your-google-client-id"
echo ""

echo "📋 PASO 1: Actualizar .env"
echo "=========================="
echo "1. Abre el archivo .env"
echo "2. Cambia esta línea:"
echo "   GOOGLE_CLIENT_ID=169191147456-776mv4fff2f81rp76jig5dpc39604ht7.apps.googleusercontent.com"
echo "   Por esta:"
echo "   GOOGLE_CLIENT_ID=your-google-client-id"
echo ""

echo "📋 PASO 2: Verificar configuración"
echo "=================================="
echo "1. Verifica que tengas en .env:"
echo "   VITE_FIREBASE_API_KEY=AIzaSyD99fYsZaNO5ystn7bOdy20dTWpErQVoz8"
echo "   VITE_FIREBASE_AUTH_DOMAIN=sensa-os-ac840.firebaseapp.com"
echo "   VITE_FIREBASE_PROJECT_ID=sensa-os-ac840"
echo "   VITE_FIREBASE_STORAGE_BUCKET=sensa-os-ac840.firebasestorage.app"
echo "   VITE_FIREBASE_MESSAGING_SENDER_ID=your-project-id"
echo "   VITE_FIREBASE_APP_ID=1:your-project-id:web:2b115f20a44c131b2fdcb4"
echo "   GOOGLE_CLIENT_ID=your-google-client-id"
echo "   GOOGLE_CLIENT_SECRET=your-google-client-secret"
echo ""

echo "📋 PASO 3: Reiniciar servidores"
echo "==============================="
echo "1. Detén el backend (Ctrl+C)"
echo "2. Detén el frontend (Ctrl+C)"
echo "3. Reinicia el backend: cd server && npm run dev"
echo "4. Reinicia el frontend: npm run dev"
echo ""

echo "🎯 Estado esperado:"
echo "=================="
echo "✅ Client ID actualizado correctamente"
echo "✅ APIs habilitadas (Calendar y Gmail)"
echo "✅ Firebase configurado"
echo "✅ Calendario muestra eventos reales"
echo "✅ Email muestra emails reales"
echo ""

echo "🚀 Para probar:"
echo "==============="
echo "1. Actualiza el .env con el Client ID correcto"
echo "2. Reinicia ambos servidores"
echo "3. Haz login con Google"
echo "4. Ve a Calendario y Email"
echo "5. Deberías ver datos reales de Google"
echo ""

echo "⚠️ Nota: El Client ID debe coincidir exactamente con el de Google Cloud Console."
echo "   Si no coincide, la autenticación fallará."
